<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SidemenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-view-dashboard",
            "name"=>"Dashboard",
            "link"=>"/dashboard",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>0,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>1,
            "icon"=>"mdi-settings",
            "name"=>"Settings",
            "link"=>"",
            "type"=>0,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>1,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>3,
            "icon"=>"mdi-format-list-checks",
            "name"=>"Roles",
            "link"=>"/roles",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>1,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);

        
       
        DB::table('sidemenus')->insert([
            "module_id"=>2,
            "icon"=>"mdi-account-multiple",
            "name"=>"Users",
            "link"=>"/users",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>5,
            "icon"=>"mdi-animation",
            "name"=>"Modules",
            "link"=>"/modules",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>3,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>5,
            "icon"=>"mdi-border-left",
            "name"=>"Side Menus",
            "link"=>"/sidemenus",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>6,
            "icon"=>"mdi-school",
            "name"=>"School",
            "link"=>"/schools",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>5,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>7,
            "icon"=>"mdi-source-branch",
            "name"=>"Branch",
            "link"=>"/branches",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>6,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);

        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-format-list-checks",
            "name"=>"Status",
            "link"=>"/statuses",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>7,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-stairs",
            "name"=>"Stage",
            "link"=>"/stages",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>8,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-facebook",
            "name"=>"Source",
            "link"=>"/sources",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>9,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-grid",
            "name"=>"Category",
            "link"=>"/categories",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>10,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-package-variant",
            "name"=>"Product",
            "link"=>"/products",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>11,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>13,
            "icon"=>"mdi-package-variant",
            "name"=>"Lead",
            "link"=>"/leads",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>2,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>8,
            "icon"=>"mdi-account-group-outline",
            "name"=>"My Referral",
            "link"=>"/myReferrals",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>3,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>9,
            "icon"=>"mdi-format-list-checks",
            "name"=>"PaymentStatus",
            "link"=>"/paymentStatuses",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>12,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>10,
            "icon"=>"mdi-format-list-checks",
            "name"=>"ReferralStatus",
            "link"=>"/referralStatuses",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>13,
            "parentId"=>2,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>11,
            "icon"=>"mdi-account-group",
            "name"=>"Referral",
            "link"=>"/referrals",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>12,
            "icon"=>"mdi-account-cash",
            "name"=>"Commission",
            "link"=>"/commissions",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>14,
            "icon"=>"mdi-file-document",
            "name"=>"All Referrer",
            "link"=>"/allReferrals",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>15,
            "icon"=>"mdi-file-document",
            "name"=>"Weekly Report",
            "link"=>"/weeklyReportReferrals",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
        DB::table('sidemenus')->insert([
            "module_id"=>16,
            "icon"=>"mdi-file-document",
            "name"=>"All Payment",
            "link"=>"/commissionPayments",
            "type"=>1,
            "status"=>1,
            "deleted_at"=>null,
            "ordering"=>4,
            "parentId"=>0,
            "is_report"=>0,
            'created_by'=>1,
        ]);
    }
}
